server {
    listen 51980; # 容器内部 Web 服务端口，不对外映射
    # listen [::]:51980;

    client_max_body_size 4096m;

    location / {
        rewrite ^/(.*)$ /ui/$1 last;
    }

    include includes/*.conf;
}
