server {
    listen 51980; # 如果不开启 https, 这里会 sed 成 80
    # listen [::]:51980;

    client_max_body_size 4096m;

    location / {
        rewrite ^/(.*)$ /ui/$1 last;
    }

    include includes/*.conf;
}
