ARG VERSION=dev
FROM jumpserver/web-static:20240801_063928 AS static
FROM jumpserver/web:${VERSION}-ce

ARG DEPENDENCIES="                    \
        curl                          \
        vim"

ARG APK_MIRROR=dl-cdn.alpinelinux.org
RUN sed -i "s/dl-cdn.alpinelinux.org/${APK_MIRROR}/g" /etc/apk/repositories \
    && apk add --no-cache ${DEPENDENCIES}

COPY --from=static /opt/ /opt/
