server {
    listen 80;
    # listen [::]:80;
    # server_name demo.jumpserver.org;  # 取消注释并自行修改成你自己的域名

    client_max_body_size 4096m;

    location / {
        rewrite ^/(.*)$ /ui/$1 last;
    }

    include includes/*.conf;
}
