name: "build-test"
on: [push]

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ilteoood/docker_buildx@master
      id: test
      with:
        imageName: jumpserver/web
        dockerFile: Dockerfile

    - uses: LouisBrunner/checks-action@v1.5.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Check Build
        conclusion: ${{ job.status }}
        output: |
          {"summary": ""}}
