name: create deployment

on:
  push:
    branches:
      - pr@*
  pull_request:
    branches:
      - pr@*
  workflow_dispatch:

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: LouisBrunner/checks-action@v1.3.1
      id: check
      with:
        sha: ${{ github.sha }}
        token: ${{ github.token }}
        name: Second Job
        status: in_progress

    - uses: LouisBrunner/checks-action@v1.3.1
      if: failure()
      with:
        sha: ${{ github.sha }}
        token: ${{ github.token }}
        name: Second Job
        conclusion: ${{ job.status }}
        output: |
          {"summary":""}
